// ============================================================
// DONNÉES AUTEURS - Printemps du Livre de Montaigu 2026
// ------------------------------------------------------------
// Données vérifiées et complétées par Paul ALBERT
// (présences matin/aprem ajoutées et stands corrigés)
//
// FORMAT :
//   v / s / d : true (toute la journée) | "matin" | "aprem" | false (absent)
// ============================================================

const AUTEURS = [

  // ─── AUTEURS GÉNÉRALISTE - LIBRAIRES ─────────────────────────
  { name: "Adeline DA CRUZ", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: true },
  { name: "Adèle FUGÈRE", cat: "generaliste", source: "libraire", stand: "D", v: true, s: true, d: true },
  { name: "Alexia STRESI", cat: "generaliste", source: "libraire", stand: "D", v: false, s: true, d: "matin" },
  { name: "Alix DE SAINT-ANDRÉ", cat: "generaliste", source: "libraire", stand: "E", v: "aprem", s: true, d: true },
  { name: "Anaël CALMEL-TRAIN", cat: "generaliste", source: "libraire", stand: "C", v: false, s: false, d: true },
  { name: "Angélina DELCROIX", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: true },
  { name: "Anna MCPARTLIN", cat: "generaliste", source: "libraire", stand: "E", v: true, s: true, d: "matin" },
  { name: "Anne-Marie PRÉAULT", cat: "generaliste", source: "libraire", stand: "D", v: false, s: false, d: true },
  { name: "Arnaud DE LA GRANGE", cat: "generaliste", source: "libraire", stand: "C", v: "aprem", s: true, d: true },
  { name: "Audrey ALWETT", cat: "generaliste", source: "libraire", stand: "A", v: false, s: true, d: true },
  { name: "Aurélie VALOGNES", cat: "generaliste", source: "libraire", stand: "D", v: true, s: true, d: false },
  { name: "Aurélie VIOLLIER-PERROT", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: true },
  { name: "Benjamin FOGEL", cat: "generaliste", source: "libraire", stand: "E", v: true, s: true, d: true },
  { name: "Boualem SANSAL", cat: "generaliste", source: "libraire", stand: "D", v: true, s: true, d: "matin", highlight: "Académie française" },
  { name: "Brice HOMS", cat: "generaliste", source: "libraire", stand: "D", v: "aprem", s: true, d: "matin" },
  { name: "Camille EMMANUELLE", cat: "generaliste", source: "libraire", stand: "D", v: "aprem", s: true, d: false },
  { name: "Carène PONTE", cat: "generaliste", source: "libraire", stand: "B", v: "aprem", s: true, d: true },
  { name: "Christian BRÛLARD", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: false },
  { name: "Christophe BOLTANSKI", cat: "generaliste", source: "libraire", stand: "C", v: false, s: "aprem", d: true },
  { name: "Christophe DUBOIS", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: true },
  { name: "Christophe MOLMY", cat: "generaliste", source: "libraire", stand: "B", v: true, s: true, d: false },
  { name: "Christopher LAQUIEZE", cat: "generaliste", source: "libraire", stand: "E", v: "aprem", s: true, d: true },
  { name: "Claire LEOST", cat: "generaliste", source: "libraire", stand: "D", v: false, s: true, d: true },
  { name: "Clarisse SABARD", cat: "generaliste", source: "libraire", stand: "A", v: "aprem", s: true, d: "matin" },
  { name: "Clémence CHAMBESLIN", cat: "generaliste", source: "libraire", stand: "D", v: false, s: true, d: true },
  { name: "Cynthia KAFKA", cat: "generaliste", source: "libraire", stand: "B", v: "aprem", s: true, d: true },
  { name: "Cyriaque GRIFFON", cat: "generaliste", source: "libraire", stand: "C", v: true, s: true, d: true },
  { name: "Céline DENJEAN", cat: "generaliste", source: "libraire", stand: "B", v: true, s: true, d: "matin" },
  { name: "Delphine GIRAUD", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: true },
  { name: "Didier DECOIN", cat: "generaliste", source: "libraire", stand: "C", v: true, s: true, d: true, highlight: "Président d'honneur" },
  { name: "Dominique DURAND", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: true },
  { name: "Dorothée SAINT-PAUL", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: true },
  { name: "Fany SIMON", cat: "generaliste", source: "libraire", stand: "C", v: true, s: true, d: true },
  { name: "Florent OISEAU", cat: "generaliste", source: "libraire", stand: "E", v: false, s: true, d: "matin" },
  { name: "Franz-Olivier GIESBERT", cat: "generaliste", source: "libraire", stand: "A", v: true, s: false, d: false },
  { name: "François GUICHARD", cat: "generaliste", source: "libraire", stand: "C", v: "aprem", s: true, d: true },
  { name: "Frédéric ALBERT", cat: "generaliste", source: "libraire", stand: "E", v: true, s: false, d: false },
  { name: "Gavin's CLEMENTE RUIZ", cat: "generaliste", source: "libraire", stand: "E", v: true, s: true, d: "matin" },
  { name: "Gaëlle NOHANT", cat: "generaliste", source: "libraire", stand: "E", v: "aprem", s: true, d: false },
  { name: "Gilles MARCHAND", cat: "generaliste", source: "libraire", stand: "D", v: true, s: true, d: "matin" },
  { name: "Gilles PARIS", cat: "generaliste", source: "libraire", stand: "C", v: true, s: true, d: "matin" },
  { name: "Grégory NICOLAS", cat: "generaliste", source: "libraire", stand: "B", v: true, s: true, d: true },
  { name: "Gwenaël BULTEAU", cat: "generaliste", source: "libraire", stand: "E", v: false, s: false, d: true },
  { name: "Gérard SANSEY", cat: "generaliste", source: "libraire", stand: "C", v: false, s: false, d: true },
  { name: "Henri LŒVENBRUCK", cat: "generaliste", source: "libraire", stand: "D", v: "aprem", s: true, d: "matin" },
  { name: "Hervé LE ROCH", cat: "generaliste", source: "libraire", stand: "B", v: false, s: false, d: true },
  { name: "Isabelle KREIDI", cat: "generaliste", source: "libraire", stand: "A", v: false, s: false, d: true },
  { name: "Isabelle LAGARRIGUE", cat: "generaliste", source: "libraire", stand: "E", v: "aprem", s: true, d: "matin" },
  { name: "J.B BEDUNEAU", cat: "generaliste", source: "libraire", stand: "E", v: false, s: false, d: true },
  { name: "Jacques RAVENNE", cat: "generaliste", source: "libraire", stand: "D", v: false, s: true, d: true },
  { name: "Jamy GOURMAUD", cat: "generaliste", source: "libraire", stand: "A", v: false, s: true, d: true },
  { name: "Jean-Christophe PAILLÉ", cat: "generaliste", source: "libraire", stand: "B", v: false, s: false, d: true },
  { name: "Jean-Luc BIZIEN", cat: "generaliste", source: "libraire", stand: "E", v: true, s: true, d: true },
  { name: "Jean-Philippe DAGUERRE", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: "matin" },
  { name: "Jerem'illustrations", cat: "bd", source: "libraire", stand: "13", v: false, s: false, d: true, highlight: "" },
  { name: "Johan VINCENT", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: false },
  { name: "Joseph MACÉ-SCARON", cat: "generaliste", source: "libraire", stand: "B", v: true, s: true, d: true },
  { name: "Julien SANDREL", cat: "generaliste", source: "libraire", stand: "E", v: false, s: true, d: "matin" },
  { name: "Kalindi RAMPHUL", cat: "generaliste", source: "libraire", stand: "D", v: true, s: true, d: "matin" },
  { name: "Karine REYSSET", cat: "generaliste", source: "libraire", stand: "D", v: false, s: true, d: true },
  { name: "Karine SULPICE", cat: "generaliste", source: "libraire", stand: "C", v: "aprem", s: true, d: "matin" },
  { name: "Katell FARIA", cat: "generaliste", source: "libraire", stand: "C", v: true, s: true, d: true },
  { name: "LE LIBRAIRE SE CACHE", cat: "generaliste", source: "libraire", stand: "B", v: false, s: true, d: true },
  { name: "Laure MANEL", cat: "generaliste", source: "libraire", stand: "C", v: "aprem", s: true, d: true },
  { name: "Laure POGGIOLI", cat: "generaliste", source: "libraire", stand: "E", v: true, s: false, d: false },
  { name: "Laurence CHEVALLIER", cat: "generaliste", source: "libraire", stand: "D", v: false, s: false, d: true },
  { name: "Laurent CHARLIOT", cat: "generaliste", source: "libraire", stand: "C", v: true, s: true, d: true },
  { name: "Laurent NUNEZ", cat: "generaliste", source: "libraire", stand: "E", v: true, s: true, d: true },
  { name: "Liane FOLY", cat: "generaliste", source: "libraire", stand: "B", v: "aprem", s: true, d: false },
  { name: "Lisa ROMAIN", cat: "generaliste", source: "libraire", stand: "C", v: true, s: true, d: "matin" },
  { name: "Lorraine FOUCHET", cat: "generaliste", source: "libraire", stand: "A", v: "aprem", s: true, d: false },
  { name: "Louis RAYMOND", cat: "generaliste", source: "libraire", stand: "E", v: false, s: true, d: true, highlight: "Lauréat Prix Ouest 2026" },
  { name: "Loïc FINAZ", cat: "generaliste", source: "libraire", stand: "C", v: "aprem", s: true, d: "matin", highlight: "Écrivain de Marine" },
  { name: "Mac LESGGY", cat: "generaliste", source: "libraire", stand: "B", v: true, s: true, d: false },
  { name: "Marcel GRELET", cat: "generaliste", source: "libraire", stand: "D", v: false, s: false, d: true },
  { name: "Marie VAREILLE", cat: "generaliste", source: "libraire", stand: "E", v: false, s: true, d: false },
  { name: "Marie-France DESMARAY", cat: "generaliste", source: "libraire", stand: "A", v: true, s: false, d: true },
  { name: "Mathilde BEAUSSAULT", cat: "generaliste", source: "libraire", stand: "E", v: false, s: true, d: false },
  { name: "Max MONNEHAY", cat: "generaliste", source: "libraire", stand: "B", v: false, s: true, d: false },
  { name: "Meï LEPAGE", cat: "generaliste", source: "libraire", stand: "D", v: "aprem", s: true, d: false },
  { name: "Michel BUSSI", cat: "generaliste", source: "libraire", stand: "A", v: true, s: false, d: false },
  { name: "Michelle MAZOUÉ", cat: "generaliste", source: "libraire", stand: "B", v: false, s: false, d: true },
  { name: "Michèle HALBERSTADT", cat: "generaliste", source: "libraire", stand: "D", v: true, s: true, d: false },
  { name: "Mireille CALMEL", cat: "generaliste", source: "libraire", stand: "D", v: false, s: true, d: true },
  { name: "Mo MALØ", cat: "generaliste", source: "libraire", stand: "E", v: true, s: true, d: "matin" },
  { name: "Natacha CALESTRÉMÉ", cat: "generaliste", source: "libraire", stand: "A", v: "aprem", s: true, d: true },
  { name: "Nathalie SAINT-CRICQ", cat: "generaliste", source: "libraire", stand: "C", v: false, s: "aprem", d: true },
  { name: "Naëlle CHARLES", cat: "generaliste", source: "libraire", stand: "E", v: true, s: true, d: false },
  { name: "Nicolas DRUART", cat: "generaliste", source: "libraire", stand: "B", v: true, s: true, d: true },
  { name: "Olivier ADAM", cat: "generaliste", source: "libraire", stand: "D", v: false, s: "aprem", d: "matin" },
  { name: "Olivier CASAS", cat: "generaliste", source: "libraire", stand: "D", v: true, s: false, d: false },
  { name: "Olivier DELACROIX", cat: "generaliste", source: "libraire", stand: "C", v: false, s: true, d: false },
  { name: "Patrice DUHAMEL", cat: "generaliste", source: "libraire", stand: "C", v: false, s: "aprem", d: true },
  { name: "Patrice FRANCESCHI", cat: "generaliste", source: "libraire", stand: "C", v: "aprem", s: true, d: true, highlight: "Écrivain de Marine" },
  { name: "Pauline BILISARI", cat: "generaliste", source: "libraire", stand: "D", v: true, s: true, d: "matin" },
  { name: "Philippe CHAUVET", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: true },
  { name: "Renaud LEBLOND", cat: "generaliste", source: "libraire", stand: "D", v: true, s: true, d: "matin" },
  { name: "Rémi DE MONTEVILLE", cat: "generaliste", source: "libraire", stand: "C", v: "aprem", s: "aprem", d: false },
  { name: "Sandrine DESTOMBES", cat: "generaliste", source: "libraire", stand: "D", v: true, s: true, d: "matin" },
  { name: "Sonja DELZONGLE", cat: "generaliste", source: "libraire", stand: "B", v: true, s: true, d: "matin" },
  { name: "Sophie JOMAIN", cat: "generaliste", source: "libraire", stand: "B", v: "aprem", s: true, d: "matin" },
  { name: "Sophie ROUVIER", cat: "generaliste", source: "libraire", stand: "C", v: "aprem", s: true, d: true },
  { name: "Sophie TAL MEN", cat: "generaliste", source: "libraire", stand: "B", v: "aprem", s: "aprem", d: true },
  { name: "Stephene GILLIEUX", cat: "generaliste", source: "libraire", stand: "D", v: "aprem", s: true, d: true },
  { name: "Stéphanie GUÉNOT", cat: "generaliste", source: "libraire", stand: "A", v: false, s: false, d: true },
  { name: "Stéphanie PEREZ", cat: "generaliste", source: "libraire", stand: "D", v: true, s: true, d: true },
  { name: "Séréna GIULIANO", cat: "generaliste", source: "libraire", stand: "D", v: false, s: true, d: "matin" },
  { name: "Séverine CRESSAN", cat: "generaliste", source: "libraire", stand: "D", v: "aprem", s: true, d: false },
  { name: "Xavier DE MOULINS", cat: "generaliste", source: "libraire", stand: "D", v: false, s: true, d: false },
  { name: "Xavier MARTIN", cat: "generaliste", source: "libraire", stand: "B", v: false, s: false, d: true },
  { name: "Yasmina KHADRA", cat: "generaliste", source: "libraire", stand: "E", v: "aprem", s: "aprem", d: false },
  { name: "Yves VIOLLIER", cat: "generaliste", source: "libraire", stand: "A", v: true, s: true, d: true },
  { name: "Zoe BRISBY", cat: "generaliste", source: "libraire", stand: "C", v: true, s: true, d: false },
  { name: "Éléna MACHU", cat: "generaliste", source: "libraire", stand: "E", v: false, s: false, d: true },
  { name: "Éric-Emmanuel SCHMITT", cat: "generaliste", source: "libraire", stand: "B", v: false, s: "aprem", d: true },

  // ─── AUTEURS JEUNESSE - LIBRAIRES ────────────────────────────
  { name: "Agnès GUILLON ROBIN", cat: "jeunesse", source: "libraire", stand: "H", v: false, s: false, d: true },
  { name: "Anne DUMERGUE", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: true },
  { name: "Anne GOSCINNY", cat: "jeunesse", source: "libraire", stand: "H", v: false, s: true, d: true },
  { name: "Aude MAUREL", cat: "jeunesse", source: "libraire", stand: "I", v: false, s: false, d: true },
  { name: "Aurélie GARNIER", cat: "jeunesse", source: "libraire", stand: "H", v: false, s: false, d: true },
  { name: "Benoît GRELAUD", cat: "jeunesse", source: "libraire", stand: "H", v: false, s: false, d: true },
  { name: "CHEVALIER GAMBETTE", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: "matin" },
  { name: "Cassandra O'DONNELL", cat: "jeunesse", source: "libraire", stand: "I", v: "aprem", s: true, d: false },
  { name: "Christine BEIGEL", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: "matin" },
  { name: "Christine ROUSSEY", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: "matin" },
  { name: "CÉLUNE", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: "matin" },
  { name: "David GUYON", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: false, d: false },
  { name: "GEORGETTE", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: "matin" },
  { name: "Gaël AYMON", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: false },
  { name: "Hélène CICA", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: false },
  { name: "KROCUI", cat: "jeunesse", source: "libraire", stand: "I", v: true, s: true, d: false },
  { name: "LILI LA BALEINE", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: true },
  { name: "Laëtitia SIVI", cat: "jeunesse", source: "libraire", stand: "I", v: false, s: true, d: true },
  { name: "MATHIS", cat: "jeunesse", source: "libraire", stand: "H", v: false, s: false, d: true },
  { name: "Manon BUCCIARELLI", cat: "jeunesse", source: "libraire", stand: "I", v: false, s: true, d: true },
  { name: "Manon FARGETTON", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: true },
  { name: "Marion ARBONA", cat: "jeunesse", source: "libraire", stand: "I", v: true, s: true, d: "matin" },
  { name: "Marion COCKLICO", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: "matin" },
  { name: "Martin MEYRONNE", cat: "jeunesse", source: "libraire", stand: "I", v: true, s: true, d: true },
  { name: "Mélanie GUYARD", cat: "jeunesse", source: "libraire", stand: "I", v: true, s: true, d: true },
  { name: "Nathalie LESCAILLE", cat: "jeunesse", source: "libraire", stand: "H", v: "aprem", s: true, d: "matin" },
  { name: "Pascale PERRIER", cat: "jeunesse", source: "libraire", stand: "I", v: true, s: true, d: false },
  { name: "Stéphanie BLAKE", cat: "jeunesse", source: "libraire", stand: "I", v: false, s: "aprem", d: true },
  { name: "Séverine CORDIER", cat: "jeunesse", source: "libraire", stand: "I", v: false, s: true, d: true },
  { name: "Véronique MACIEJAK", cat: "jeunesse", source: "libraire", stand: "H", v: true, s: true, d: false },

  // ─── AUTEURS BD - LIBRAIRES ──────────────────────────────────
  { name: "Alexandre ARLÈNE", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: true, d: true },
  { name: "Anaïs SCHENKÉ", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: true, d: true },
  { name: "BONES", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: true, d: "matin" },
  { name: "Carine HINDER", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: true, d: true, highlight: "Illustratrice expo Brume" },
  { name: "DJET", cat: "bd", source: "libraire", stand: "G", v: true, s: true, d: false },
  { name: "Désirée et Alain FRAPPIER", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: true, d: true },
  { name: "Elisabeth JAMMES", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: true, d: "matin" },
  { name: "Emy BILL", cat: "bd", source: "libraire", stand: "G", v: false, s: true, d: true },
  { name: "Fabien ÖCKTO LAMBERT", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: true, d: true },
  { name: "Germano GIORGIANI", cat: "bd", source: "libraire", stand: "F", v: false, s: true, d: true },
  { name: "Gilles CAZAUX", cat: "bd", source: "libraire", stand: "F", v: true, s: true, d: true },
  { name: "Guillaume LEBLANC", cat: "bd", source: "libraire", stand: "G", v: false, s: true, d: true },
  { name: "HARDOC", cat: "bd", source: "libraire", stand: "G", v: true, s: true, d: "matin" },
  { name: "Hubert MAURY", cat: "bd", source: "libraire", stand: "F", v: true, s: true, d: true },
  { name: "IZABO", cat: "bd", source: "libraire", stand: "G", v: true, s: true, d: "matin" },
  { name: "JOREN", cat: "bd", source: "libraire", stand: "G", v: true, s: false, d: true },
  { name: "Johan CORGIÉ", cat: "bd", source: "libraire", stand: "G", v: false, s: true, d: false },
  { name: "Julien STREISSEL", cat: "bd", source: "libraire", stand: "F", v: true, s: false, d: true },
  { name: "Juliette VAAST", cat: "bd", source: "libraire", stand: "G", v: "aprem", s: true, d: true },
  { name: "Lucie CASTEL", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: "aprem", d: false },
  { name: "Léa HYBRE", cat: "bd", source: "libraire", stand: "G", v: true, s: true, d: "matin" },
  { name: "MATHOU", cat: "bd", source: "libraire", stand: "G", v: false, s: true, d: false },
  { name: "Marie BAUDET", cat: "bd", source: "libraire", stand: "G", v: true, s: true, d: false },
  { name: "Mark EACERSALL", cat: "bd", source: "libraire", stand: "G", v: true, s: true, d: "matin" },
  { name: "Olivier HUCHET", cat: "bd", source: "libraire", stand: "F", v: true, s: false, d: true },
  { name: "Olivier PERRET", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: true, d: "matin" },
  { name: "POG", cat: "bd", source: "libraire", stand: "G", v: true, s: true, d: true },
  { name: "Quentin GIRARDCLOS", cat: "bd", source: "libraire", stand: "G", v: true, s: true, d: true },
  { name: "Serge PERROTIN", cat: "bd", source: "libraire", stand: "F", v: false, s: true, d: true },
  { name: "Séverine DE LA CROIX", cat: "bd", source: "libraire", stand: "G", v: "aprem", s: true, d: "matin" },
  { name: "Xavier BÉTAUCOURT", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: true, d: "matin" },
  { name: "YOANN", cat: "bd", source: "libraire", stand: "F", v: "aprem", s: true, d: true },
  { name: "Younn LOCARD", cat: "bd", source: "libraire", stand: "G", v: false, s: "aprem", d: false },

  // ─── AUTEURS GÉNÉRALISTE - MAISONS D'ÉDITION ────────────────
  { name: "Adeline VAILLANT", cat: "generaliste", source: "edition", stand: "13", v: false, s: "aprem", d: false },
  { name: "Alain PERROCHEAU", cat: "generaliste", source: "edition", stand: "1", v: false, s: "aprem", d: false },
  { name: "Anaïs M. HELLBÉ", cat: "generaliste", source: "edition", stand: "9", v: true, s: true, d: true },
  { name: "Angéline NEAU", cat: "generaliste", source: "edition", stand: "7", v: "matin", s: false, d: false },
  { name: "Anne-Marie DE RAIGNIAC", cat: "generaliste", source: "edition", stand: "4", v: true, s: true, d: true },
  { name: "Anne-Sophie CHAUVET", cat: "generaliste", source: "edition", stand: "16", v: true, s: true, d: false },
  { name: "Arnaud BROCHARD", cat: "generaliste", source: "edition", stand: "1-samedi / 16- dimanche", v: true, s: "aprem", d: true },
  { name: "Arnaud DRUELLE", cat: "generaliste", source: "edition", stand: "10", v: true, s: true, d: true },
  { name: "Aude FRANC", cat: "generaliste", source: "edition", stand: "16", v: true, s: true, d: false },
  { name: "Aude ZIEGELMEYER", cat: "generaliste", source: "edition", stand: "10", v: "aprem", s: true, d: true },
  { name: "Benoît PINEAU", cat: "generaliste", source: "edition", stand: "7", v: false, s: true, d: false },
  { name: "Bernard GRASSET", cat: "generaliste", source: "edition", stand: "1", v: false, s: false, d: "matin" },
  { name: "Blanche COLLANGE", cat: "generaliste", source: "edition", stand: "16", v: false, s: true, d: true },
  { name: "Catherine GIRARD-AUGRY", cat: "generaliste", source: "edition", stand: "1", v: false, s: false, d: "aprem" },
  { name: "Chloé GUILLOT-ELOUARD", cat: "generaliste", source: "edition", stand: "9", v: false, s: true, d: true },
  { name: "Christian HARDY", cat: "generaliste", source: "edition", stand: "1", v: "aprem", s: false, d: false },
  { name: "Clotilde JANNIN", cat: "generaliste", source: "edition", stand: "16", v: "aprem", s: true, d: false },
  { name: "Coline DUPUY", cat: "generaliste", source: "edition", stand: "16", v: true, s: false, d: false },
  { name: "Constance DORLET", cat: "generaliste", source: "edition", stand: "7", v: false, s: false, d: true },
  { name: "Cécile MESLIN", cat: "generaliste", source: "edition", stand: "12", v: false, s: true, d: true },
  { name: "Daniel BAAL", cat: "generaliste", source: "edition", stand: "17", v: false, s: "aprem", d: false },
  { name: "Delphine MARCHAL", cat: "generaliste", source: "edition", stand: "2", v: false, s: false, d: true },
  { name: "Denys EZQUERRA", cat: "generaliste", source: "edition", stand: "5", v: true, s: true, d: true },
  { name: "Dominique RAIMBOURG", cat: "generaliste", source: "edition", stand: "7", v: "aprem", s: false, d: true },
  { name: "Ed TELLIAM", cat: "generaliste", source: "edition", stand: "1", v: false, s: "matin", d: false },
  { name: "Elena DELECOURT", cat: "generaliste", source: "edition", stand: "12", v: "matin", s: false, d: false },
  { name: "Etienne TRITT", cat: "generaliste", source: "edition", stand: "13", v: false, s: "aprem", d: false },
  { name: "FANTOUMI", cat: "generaliste", source: "edition", stand: "1", v: false, s: false, d: true },
  { name: "Fabienne BILLON", cat: "generaliste", source: "edition", stand: "12", v: false, s: true, d: false },
  { name: "Florence GINDRE", cat: "generaliste", source: "edition", stand: "9", v: true, s: true, d: true },
  { name: "François BOSSIS", cat: "generaliste", source: "edition", stand: "13", v: false, s: false, d: "matin" },
  { name: "Gabriel BOUVET", cat: "generaliste", source: "edition", stand: "12", v: false, s: "aprem", d: false },
  { name: "Gaëlle CHARRIER-BRETAGNE", cat: "generaliste", source: "edition", stand: "2", v: true, s: true, d: true },
  { name: "Gaëlle TERTRAIS", cat: "generaliste", source: "edition", stand: "16", v: false, s: "matin", d: false },
  { name: "Gilbert MÉTIVIER", cat: "generaliste", source: "edition", stand: "1", v: "aprem", s: false, d: false },
  { name: "Grégory BONNEAU", cat: "generaliste", source: "edition", stand: "1", v: false, s: "matin", d: false },
  { name: "Guylaine BURGAUD", cat: "generaliste", source: "edition", stand: "1", v: false, s: false, d: "aprem" },
  { name: "Gwladys BERTRAND", cat: "generaliste", source: "edition", stand: "11", v: false, s: false, d: true },
  { name: "Henri MARIEL", cat: "generaliste", source: "edition", stand: "12", v: true, s: true, d: true },
  { name: "Hervé LE ROCH (édition)", cat: "generaliste", source: "edition", stand: "16", v: true, s: true, d: false },
  { name: "Hervé MACÉ", cat: "generaliste", source: "edition", stand: "3", v: true, s: true, d: true },
  { name: "Hervé RETUREAU", cat: "generaliste", source: "edition", stand: "3", v: false, s: true, d: false },
  { name: "Hélène GOURLAIN", cat: "generaliste", source: "edition", stand: "1", v: false, s: "aprem", d: false },
  { name: "Hélène KÉRILLIS", cat: "generaliste", source: "edition", stand: "12", v: true, s: true, d: true },
  { name: "Jacques DE VILLIERS", cat: "generaliste", source: "edition", stand: "16", v: false, s: "aprem", d: "aprem" },
  { name: "Jacques SOIGNON", cat: "generaliste", source: "edition", stand: "11", v: false, s: false, d: true },
  { name: "Jean DE RAIGNIAC", cat: "generaliste", source: "edition", stand: "4", v: true, s: true, d: true },
  { name: "Jean-Christophe PAILLÉ (édition)", cat: "generaliste", source: "edition", stand: "1", v: false, s: false, d: "matin" },
  { name: "Jean-Claude LUMET", cat: "generaliste", source: "edition", stand: "13", v: "aprem", s: false, d: "aprem" },
  { name: "Jean-François HENRY", cat: "generaliste", source: "edition", stand: "1", v: false, s: "aprem", d: true },
  { name: "Jean-Pierre BOUREAU", cat: "generaliste", source: "edition", stand: "1", v: true, s: false, d: false },
  { name: "Johann PAILLOUX", cat: "generaliste", source: "edition", stand: "11", v: false, s: false, d: true },
  { name: "Laurence PAIN", cat: "generaliste", source: "edition", stand: "7", v: false, s: true, d: false },
  { name: "Luc TURLAN", cat: "generaliste", source: "edition", stand: "3", v: true, s: true, d: true },
  { name: "Lys KRYSLER", cat: "generaliste", source: "edition", stand: "10", v: true, s: true, d: true },
  { name: "Marcel GRELET (édition)", cat: "generaliste", source: "edition", stand: "2", v: true, s: true, d: false },
  { name: "Marianne HUVET", cat: "generaliste", source: "edition", stand: "1", v: "matin", s: false, d: false },
  { name: "Marie FARDET", cat: "generaliste", source: "edition", stand: "12  - vendredi aprem / 16 - vendredi matin et samedi", v: true, s: true, d: false },
  { name: "Marie OSMOND", cat: "generaliste", source: "edition", stand: "12", v: true, s: true, d: true },
  { name: "Marie-José DUCHAINE", cat: "generaliste", source: "edition", stand: "1", v: "aprem", s: false, d: false },
  { name: "Martial LIMOUZIN", cat: "generaliste", source: "edition", stand: "16", v: true, s: true, d: true },
  { name: "Michel CHATRY", cat: "generaliste", source: "edition", stand: "1", v: false, s: true, d: false },
  { name: "Michel PELÉ", cat: "generaliste", source: "edition", stand: "1", v: false, s: "aprem", d: false },
  { name: "Michelle MAZOUÉ (édition)", cat: "generaliste", source: "edition", stand: "1 - dimanche  / 3 - vendredi samedi", v: true, s: true, d: "aprem" },
  { name: "Mikaël DELAYEN", cat: "generaliste", source: "edition", stand: "1", v: false, s: "aprem", d: false },
  { name: "Muriel ODOYER", cat: "generaliste", source: "edition", stand: "1", v: "aprem", s: false, d: false },
  { name: "Nad' DUBRÈGE", cat: "generaliste", source: "edition", stand: "7", v: false, s: false, d: true },
  { name: "Olivier ANGEVIN", cat: "generaliste", source: "edition", stand: "1", v: false, s: "matin", d: false },
  { name: "Pascal MARIETTE", cat: "generaliste", source: "edition", stand: "5", v: false, s: true, d: false },
  { name: "Patrice GAZIER", cat: "generaliste", source: "edition", stand: "1", v: false, s: false, d: true },
  { name: "Paul DE RUGY", cat: "generaliste", source: "edition", stand: "1", v: false, s: "matin", d: false },
  { name: "Philippe BUFFAROT", cat: "generaliste", source: "edition", stand: "7", v: false, s: true, d: false },
  { name: "Philippe FÉRARD", cat: "generaliste", source: "edition", stand: "11", v: false, s: false, d: true },
  { name: "Philippe GILBERT", cat: "generaliste", source: "edition", stand: "3", v: true, s: false, d: false },
  { name: "Philippe MEYRE", cat: "generaliste", source: "edition", stand: "1", v: false, s: "matin", d: false },
  { name: "Pierre DEBERDT", cat: "generaliste", source: "edition", stand: "1", v: "matin", s: false, d: false },
  { name: "Pierre MARTIN", cat: "generaliste", source: "edition", stand: "3", v: true, s: true, d: true },
  { name: "Pierre OREFICE", cat: "generaliste", source: "edition", stand: "7", v: "aprem", s: false, d: false },
  { name: "Régine ALBERT", cat: "generaliste", source: "edition", stand: "13", v: "aprem", s: false, d: "aprem" },
  { name: "Régis PARENTEAU-DENOËL", cat: "generaliste", source: "edition", stand: "16", v: false, s: true, d: true },
  { name: "Sabrina KIEFNER", cat: "generaliste", source: "edition", stand: "1", v: true, s: false, d: false },
  { name: "Sara BERNÈDE", cat: "generaliste", source: "edition", stand: "7", v: false, s: true, d: false },
  { name: "Sarah BLAINEAU", cat: "generaliste", source: "edition", stand: "3", v: false, s: false, d: true },
  { name: "Simon BOURON", cat: "generaliste", source: "edition", stand: "1", v: false, s: false, d: "aprem" },
  { name: "TONITORFER", cat: "generaliste", source: "edition", stand: "12", v: false, s: false, d: true },
  { name: "Thomas GRAFFARD", cat: "generaliste", source: "edition", stand: "1", v: true, s: false, d: false },
  { name: "Timéa TADEBOIS", cat: "generaliste", source: "edition", stand: "7", v: false, s: false, d: true },
  { name: "Vincent DENIS", cat: "generaliste", source: "edition", stand: "11", v: false, s: false, d: true },
  { name: "Virginie LANDEMAINE", cat: "generaliste", source: "edition", stand: "12", v: true, s: true, d: true },
  { name: "Virginie MOSNERON DUPIN", cat: "generaliste", source: "edition", stand: "1", v: false, s: "aprem", d: false },
  { name: "Virginie VÉTIL", cat: "generaliste", source: "edition", stand: "7", v: false, s: false, d: true },
  { name: "Véronique HERMOUET", cat: "generaliste", source: "edition", stand: "3", v: true, s: true, d: true },
  { name: "Xavier ARMANGE", cat: "generaliste", source: "edition", stand: "1", v: false, s: false, d: "matin" },
  { name: "Yanick MESSAGER", cat: "generaliste", source: "edition", stand: "1 - samedi / 17 - vendredi dimanche", v: true, s: "aprem", d: true },
  { name: "Yannis SUIRE", cat: "generaliste", source: "edition", stand: "1", v: true, s: false, d: false },
  { name: "Yves RAGER", cat: "generaliste", source: "edition", stand: "2", v: false, s: true, d: true },
  { name: "Élodie GENDERS", cat: "generaliste", source: "edition", stand: "2", v: true, s: true, d: true },

  // ─── AUTEURS JEUNESSE - MAISONS D'ÉDITION ───────────────────
  { name: "Alice HUREAU", cat: "jeunesse", source: "edition", stand: "21", v: false, s: true, d: false },
  { name: "Benoît BROYART", cat: "jeunesse", source: "edition", stand: "18", v: false, s: true, d: false },
  { name: "Gwenaële BARUSSAUD", cat: "jeunesse", source: "edition", stand: "20", v: true, s: true, d: false },
  { name: "Jade BRÉCHET", cat: "jeunesse", source: "edition", stand: "19", v: true, s: true, d: false },
  { name: "Juliette MOZET", cat: "jeunesse", source: "edition", stand: "19", v: true, s: false, d: false },
  { name: "Louis TAILLIEZ", cat: "jeunesse", source: "edition", stand: "20", v: false, s: true, d: true },
  { name: "Oriane LESAFFRE", cat: "jeunesse", source: "edition", stand: "18", v: false, s: false, d: true },
  { name: "Sandrine FOURRIER", cat: "jeunesse", source: "edition", stand: "19", v: true, s: true, d: true },
  { name: "Servan LEGOFF", cat: "jeunesse", source: "edition", stand: "19", v: false, s: true, d: false },
  { name: "Sibylle AUDOLLENT", cat: "jeunesse", source: "edition", stand: "19", v: true, s: false, d: false },
  { name: "Valentine DU PAYRAT", cat: "jeunesse", source: "edition", stand: "21", v: "aprem", s: true, d: "matin" },
  { name: "Virginie MARTINS-B", cat: "jeunesse", source: "edition", stand: "19", v: false, s: false, d: true },
];
